language: node_js
node_js:
- 6
env:
  global:
    secure: co8o1+jeXievJo4vXSo8ZH8pfGLh9BLVIQwPrlHhrsxw5FHEBlOtJBKidj3f++wYblk9lbpiD1xaN0BKZyWXLgvW/zVdgOIZKyvlye0wFsnSe0LjJdj8j+pvd3snoQNGiFhM8GsAipJ1zAMLpekddXy14RUj7Hec2jlVV49YtY5NHE/MJudF7kCpvU4ShhDdn2bxGrjvafeqsKrELY274ZgeONE7uEK2AGJxJ/+MMWyNx+Tb4+7YzruiyUwV07KPQ0VY5rX75F7jD2+6keDPDadSuCNL1WxnsRiyo7Rk9SpOfLlwk8bkWBPbKXSuZsTbhNPkwJ4XrEFuK8bu+0qJr2LJWQLQfjgJa+s3qT9nb8hYef2wkV62yDYJ7xsnAFZJnlhxVIRlmT+xRb3XHIzwn0YF6nzYW7IBJsQyKAPGkTrF4Uirma6W0XYqzuPRNTgGCOKnOYRlQ3+XiOrkE9GZTFKL7Tv5+MG2CRA9s4NfB31HckKiboF8kQM+kQB1Ts/C4r5THiPRvS3aibIHYT1EP/AnsMT/4nOUp/5++PBNWy+bP9tYawQwc0rofCkkC8OxaNM6b35WmMPP785B3whw8zRiBj8L06M7226ojyLQLqI3yau54UdGPYYiDFI/JncQvYxIZLFI7/FH8pWekXorZOSfR2vbGv33B6dLSnmtA5w=
